# ===============================
# Promorang Worker Configuration
# ===============================
name = "promorang"
main = "src/index.ts"
compatibility_date = "2024-06-01"

routes = [
  { pattern = "api.promorang.co/*", zone_name = "promorang.co" }
]

[vars]
JWT_SECRET           = "c1119a8b8b6f12e0d95019838546c299c16d6afca88943d03da14c7cc4a541bd9"
GOOGLE_CLIENT_ID     = "732791210432-mgbf7g7r70gin2u6ccnnp4d16i76if9i.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
STRIPE_SECRET_KEY    = "sk_test_..."  # Add your Stripe secret key here
STRIPE_WEBHOOK_SECRET = "whsec_..."   # Add your Stripe webhook secret here
STRIPE_PRICE_ID_10GEMS = "price_..."   # Add your Stripe price ID for 10 gems
STRIPE_PRICE_ID_47GEMS = "price_..."   # Add your Stripe price ID for 47 gems

[[d1_databases]]
binding = "DB"
database_name = "promorang-db"
database_id = "8c099e67-c157-4573-94a2-fce17dcc0edb"
